#!/bin/bash

## Builds the ./install-nodejs-and-pm2 file from src/
## Checks that all example apps have the same js code.

set -e

DIR=$(dirname $0)

## Example apps
APPS=${DIR}/example/apps/*/releases/*/index.js
FIRST_APP=$(echo ${APPS} | cut -d ' ' -f 1)
for i in $APPS; do
  diff -q ${FIRST_APP} ${i}
done

## install-nodejs-and-pm2
SOURCE_FILE="${DIR}/src/install-nodejs-and-pm2"
TARGET_FILE="${DIR}/install-nodejs-and-pm2"

ECOSYSTEM_CONFIG_JS_FILE="${DIR}/example/apps/ecosystem.config.js"
export ECOSYSTEM_CONFIG_JS_1="$(<${ECOSYSTEM_CONFIG_JS_FILE})"
export ECOSYSTEM_CONFIG_JS_2="${ECOSYSTEM_CONFIG_JS_1//\`/\\\`}"
export ECOSYSTEM_CONFIG_JS_3="${ECOSYSTEM_CONFIG_JS_2//\"/\\\"}"
export ECOSYSTEM_CONFIG_JS="${ECOSYSTEM_CONFIG_JS_3//\$/\\$}"

ECOSYSTEM_CONFIG_JS_HELPER_JS_FILE="${DIR}/example/apps/ecosystem.config.js-helper.js"
export ECOSYSTEM_CONFIG_JS_HELPER_JS_1="$(<${ECOSYSTEM_CONFIG_JS_HELPER_JS_FILE})"
export ECOSYSTEM_CONFIG_JS_HELPER_JS_2="${ECOSYSTEM_CONFIG_JS_HELPER_JS_1//\`/\\\`}"
export ECOSYSTEM_CONFIG_JS_HELPER_JS_3="${ECOSYSTEM_CONFIG_JS_HELPER_JS_2//\"/\\\"}"
export ECOSYSTEM_CONFIG_JS_HELPER_JS="${ECOSYSTEM_CONFIG_JS_HELPER_JS_3//\$/\\$}"

envsubst '$ECOSYSTEM_CONFIG_JS $ECOSYSTEM_CONFIG_JS_HELPER_JS' < "${SOURCE_FILE}" > "${TARGET_FILE}"
