#!/usr/bin/env bash

## Installs Node.js and pm2

set -e

## Config
NODEJS_USER=nodejs
NVM_VERSION=0.33.11
NODEJS_VERSION=10

NODEJS_HOME_DIR=/var/lib/$NODEJS_USER
NVM_DIR=$NODEJS_HOME_DIR/.nvm

## Install Node.js
getent passwd | grep ^nodejs: || useradd --system --create-home --home-dir $NODEJS_HOME_DIR $NODEJS_USER
su - $NODEJS_USER -c "mkdir -p $NVM_DIR"
su - $NODEJS_USER -c "curl -o- https://raw.githubusercontent.com/creationix/nvm/v$NVM_VERSION/install.sh | bash"
su - $NODEJS_USER -c "nvm install $NODEJS_VERSION"
su - $NODEJS_USER -c "npm install -g npm"
su - $NODEJS_USER -c "npm install -g yarn"

## Install pm2
su - $NODEJS_USER -c "npm install -g pm2@latest"
su - $NODEJS_USER -c "pm2 update"
. $NVM_DIR/nvm.sh && pm2 startup systemv -u $NODEJS_USER

## Instructions
echo
echo
echo =======================================================================
echo Node.js is now installed for user $NODEJS_USER.
echo pm2 runs on boot, as user $NODEJS_USER.
echo
echo Log in as $NODEJS_USER to issue pm2 commands:
echo \# su - $NODEJS_USER
echo \$ pm2 status
echo =======================================================================
