#!/usr/bin/env bash

## Installs Node.js and pm2

set -e

## Config
NODEJS_USER=${NODEJS_USER:-nodejs}
NVM_VERSION=${NVM_VERSION:-0.33.11}
NODEJS_VERSION=${NODEJS_VERSION:-10}

NODEJS_HOME_DIR=${NODEJS_HOME_DIR:-/var/$NODEJS_USER}
NVM_DIR=${NODEJS_HOME_DIR}/.nvm

## Install Node.js
getent passwd | grep ^${NODEJS_USER}: || useradd --system --shell $(which bash) --create-home --home-dir ${NODEJS_HOME_DIR} ${NODEJS_USER}
su - ${NODEJS_USER} -c "mkdir -p $NVM_DIR"
su - ${NODEJS_USER} -c "curl -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash"
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && nvm install ${NODEJS_VERSION}"
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && nvm alias default ${NODEJS_VERSION}"
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && npm install -g npm"
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && npm install -g yarn"

## Install pm2
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && npm install -g pm2@latest"
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && pm2 update"

. ${NVM_DIR}/nvm.sh && \
    pm2 startup \
        --service-name pm2 \
        --user ${NODEJS_USER} \
        --hp ${NODEJS_HOME_DIR}

## Set up apps structure
su - ${NODEJS_USER} -c "mkdir -p apps"

if [ ! -e "${NODEJS_HOME_DIR}/apps/ecosystem.config.js" ]; then
  su - ${NODEJS_USER} -c "cat > apps/ecosystem.config.js << 'EOF'
$ECOSYSTEM_CONFIG_JS
EOF"
  echo "Created ${NODEJS_HOME_DIR}/apps/ecosystem.config.js"
else
  echo "Not overwriting existing ${NODEJS_HOME_DIR}/apps/ecosystem.config.js"
fi

if [ ! -e "${NODEJS_HOME_DIR}/apps/ecosystem.config.js-helper.js" ]; then
  echo "Creating ${NODEJS_HOME_DIR}/apps/ecosystem.config.js-helper.js"
else
  echo "Overwriting existing ${NODEJS_HOME_DIR}/apps/ecosystem.config.js-helper.js"
fi
su - ${NODEJS_USER} -c "cat > apps/ecosystem.config.js-helper.js << 'EOF'
$ECOSYSTEM_CONFIG_JS_HELPER_JS
EOF"

## Instructions
su - ${NODEJS_USER} -c ". ${NVM_DIR}/nvm.sh && node -e \"console.log(\\\`


==============================================================================
Node.js is now installed for user ${NODEJS_USER}.

This message is proof, because it is generated from within Node.js as the
${NODEJS_USER} user.

pm2 runs on boot, as user ${NODEJS_USER}.

You can manage the pm2 service like this:

    \# service pm2 status
    \# service pm2 start
    \# service pm2 stop
    \# service pm2 restart

For more pm2 commands, log in as ${NODEJS_USER}:

    \# su - ${NODEJS_USER}

Example commands, as the ${NODEJS_USER} user:

    \$ pm2 help
    \$ pm2 status
    \$ pm2 startOrReload ~/apps/ecosystem.config.js
    \$ pm2 save
    \$ pm2 dash
    \$ pm2 logs

==============================================================================
\\\`)\""
